using SharpMinerals.Level.Generator.Biomes;
using SharpMinerals.Math;

namespace SharpMinerals.Level.Generator.Features;

/// <summary>Places a feature at most once per column of the cube being generated, reading the finished cube's
/// blocks to find the surface. For single-cell features that never cross a border and want to see earlier
/// features (ground cover skipping columns capped by a tree). The default target is
/// <see cref="PlacementTarget.Solid"/>; block-reading cave targets slot in here later without changing the
/// driver.</summary>
public sealed class PerColumnPlacement : FeaturePlacement {
    public PerColumnPlacement(Feature feature) : base(feature, PlacementTarget.Solid) { }

    public override IChunkDecorator Bind(FeatureWorld world) {
        IColumnAnchors finder = Target switch {
            PlacementTarget.Solid => new SolidFinder(),
            _ => throw new InvalidOperationException(
                $"Per-column placement supports the {nameof(PlacementTarget.Solid)} target (and future cave targets); " +
                $"got {Target}."),
        };
        return new PerColumnDecorator(Feature, finder, world.Seed, world.Source, Rule, RarityDensity, RarityFeatureMap);
    }

    /// <summary>The bound per-column driver: for each column of the cube it resolves the anchor(s), gates each on
    /// rarity and the rule, and stamps.</summary>
    sealed class PerColumnDecorator : IChunkDecorator {
        const int SaltRarity = 0x01; // only consulted when a rarity is set (single-cell features usually roll in Place)
        const int SurfaceBandTop = 140; // ground cover only sits in the surface band

        readonly Feature feature;
        readonly IColumnAnchors finder;
        readonly int seed;
        readonly BiomeSource source;
        readonly SurfaceRule rule;
        readonly Func<IBiome, double>? rarityDensity;
        readonly bool rarityFeatureMap;

        public PerColumnDecorator(Feature feature, IColumnAnchors finder, int seed, BiomeSource source, SurfaceRule rule,
                                  Func<IBiome, double>? rarityDensity, bool rarityFeatureMap) {
            this.feature = feature;
            this.finder = finder;
            this.seed = seed;
            this.source = source;
            this.rule = rule;
            this.rarityDensity = rarityDensity;
            this.rarityFeatureMap = rarityFeatureMap;
        }

        public void Decorate(Chunk chunk, Vector3i cube) {
            int baseX = (int)(cube.X * Chunk.Size);
            int baseY = (int)(cube.Y * Chunk.Size);
            int size = (int)Chunk.Size;
            if (baseY + size <= WorldDefaults.SeaLevel || baseY > SurfaceBandTop) return;

            int baseZ = (int)(cube.Z * Chunk.Size);
            var sink = new CubeSink(chunk, baseX, baseY, baseZ);
            var anchors = new List<Anchor>(1);

            for (int lz = 0; lz < size; lz++)
                for (int lx = 0; lx < size; lx++) {
                    anchors.Clear();
                    finder.Find(chunk, cube, lx, lz, anchors);
                    if (anchors.Count == 0) continue;

                    int wx = baseX + lx, wz = baseZ + lz;
                    var biome = source.Dominant(wx, wz);
                    var rng = WorldRng.At(seed, wx, wz);

                    foreach (var anchor in anchors) {
                        if (rarityDensity is not null) {
                            double density = rarityDensity(biome);
                            if (density <= 0.0) continue;
                            double prob = density * (rarityFeatureMap ? source.FeatureDensity(wx, wz) : 1.0);
                            if (!rng.Chance(SaltRarity, prob)) continue;
                        }
                        var ctx = new PlaceContext(wx, wz, anchor, biome, source, rng);
                        if (!rule.Test(ctx)) continue;
                        feature.Place(ctx, sink);
                    }
                }
        }
    }
}

/// <summary>Finds the anchor(s) in one column of the cube being generated by reading its blocks. A world surface
/// yields at most one (the top solid cell); a cave target yields one per pocket. Block-reading, so it only sees
/// the current cube - not valid for a border-crossing scatter.</summary>
public interface IColumnAnchors {
    /// <summary>Appends this column's anchors (world coordinates) to <paramref name="into"/>; appends nothing for
    /// an empty column.</summary>
    void Find(Chunk cube, Vector3i cubeOrigin, int lx, int lz, ICollection<Anchor> into);
}

/// <summary>The world-surface anchor finder: the highest solid cell in the cube's column, carrying its actual
/// surface block. Yields nothing for an empty column. A surface at the cube's top layer resolves normally - the
/// feature just above it clips away in the <see cref="CubeSink"/>, exactly as writing above the ceiling would.</summary>
public sealed class SolidFinder : IColumnAnchors {
    public void Find(Chunk cube, Vector3i cubeOrigin, int lx, int lz, ICollection<Anchor> into) {
        int top = (int)Chunk.Size - 1;
        for (int ly = top; ly >= 0; ly--) {
            var block = cube.GetBlock(lx, ly, lz);
            if (block.IsAir) continue;
            int worldY = (int)(cubeOrigin.Y * Chunk.Size) + ly;
            into.Add(new Anchor(worldY, block));
            return;
        }
    }
}
